### ISSUE TITLE
Compile Paddle on Windows System

### ISSUE THREAD

**Issue by gangliao** [baidu/Paddle#290] opened 2016-10-30 11:45 UTC
Related [Project](https://github.com/baidu/Paddle/projects/6)

**Comment by wangkuiyi** [comment] 2016-10-30 20:48
@gangliao 请说明

1. 为什么会有这个需求，
1. 为了解决它需要做什么

给定这些信息，我们才有依据如何处理，比如放进哪个milestone里。

**Comment by gangliao** [comment] 2016-10-31 02:35
@wangkuiyi 
Request came from #5.
To port Paddle on Windows:

1. revise CMake to support Windows(MSVC).
2. add Win32 socket APIs for networks.
3. add Windows-related APIs for system-level stuff.
4. unite dynamic load libraries interfaces for all operating systems.
5. fix bugs and unit test on Windows.

**Comment by gangliao** [comment] 2016-10-31 02:44
Predicting how long to end this long-term work is difficult, so it's not added into any of recent milestones.

**Comment by reyoung** [comment] 2016-10-31 03:14
@gangliao  I will review them tomorrow, when I'm on duty for github issues.

Duty day is a good chance to review PR.  :-)

@wangkuiyi This feature is not associated to any milestone because we just finish to compile on Windows, but there is no continuous integration and regression test for it. Also the install package for windows should be added.

So, we should do discuss it layer when ci, install pack, etc is done.

I will add a project to tracking it.

**Comment by reyoung** [comment] 2016-10-31 03:36
@gangliao Sorry, i just notice that this is an issue, not a PR.

Is windows compile ready to send a PR now?

**Comment by gangliao** [comment] 2016-10-31 04:30
@reyoung  maybe a little bit later..

**Comment by wangkuiyi** [comment] 2016-10-31 18:11
I would suggest we deny this requirement and close this issue as well as #5. Given that Microsoft Azure is running Linux, I don't see a Windows port is anyway good for Paddle. Not even mentioning the burden to prioritize and implement it, and the work of setting up CI for it.

**Comment by wangkuiyi** [comment] 2016-11-01 04:05
I had a discussion about this issue with @emailweixu today. Given that Mac and Window can both run Docker using native virtualization mechanism, in particular,

1. Windows: https://docs.docker.com/engine/installation/windows/
1. Mac: https://docs.docker.com/engine/installation/mac/

I believe that we should encourage users to run Paddle in Docker containers on Mac and Windows.

If we see enough number of +1's accumulate in #5 in the future, we can move on working on Windows (or Mac) ports. For now, let us let focus on making Paddle runs well with Linux.

**Closed by wangkuiyi** 2016-11-01 04:05 UTC
Labels: developing, enhancement
